version: '2'
services:
  app:
    container_name: crawlerApp
    build: .
    ports:
      - "8888:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan serve --host 0.0.0.0'